version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - /home/jsales/Codes/Docker-LiveDemo/backend:/app/backend
      - logs:/app/logs
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /home/jsales/Codes/Docker-LiveDemo/frontend/src:/app/src
    depends_on:
      - backend
    stdin_open: true
    tty: true
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    
volumes:
  data:
  logs: